#!/usr/bin/bash
# Tool for copying selected gitignore in current working directory

CNORMAL="\e[0m"
CERROR="\e[31m"
CGREEN="\e[32m"

# Ensure dependencies
for prog in fzf awk; do
    if ! command -v fzf &>/dev/null ; then
        echo -e "gitignore error: ${CERROR}${prog} required${CNORMAL}"
        exit 1
    fi
done

GITIGNORE_DEST="${PWD}/.gitignore"

# Go to gitignores directory
cd "$(dirname "$(dirname "$(realpath -P "$0")")")" || exit 1

FZF_ARGS=(
    --multi
    --scheme=path
    --info=right
    --border=bottom
    --border-label='[Space/Tab]=Select entry [Enter]=Generate gitignore'
    --border-label-pos=5
    --bind='change:first,space:toggle+clear-query,tab:toggle+clear-query'
    --preview="$(command -v bat &>/dev/null && echo -n 'bat --color=always {}' || echo -n 'cat {}')"
)

#shellcheck disable=SC2016
AWK_PROGRAM='{
    name=$0
    gsub(".gitignore", "", name)
    print "###", name, "###"

    cmd="cat "
    gsub("$", $0, cmd)
    while ((cmd |& getline line) > 0)
        print line
    close(cmd)
    print "###END", name, "###"
}' 

# select and process selected gitignores
find . -name '*.gitignore' -printf '%P\n' \
    | fzf "${FZF_ARGS[@]}" \
    | awk "$AWK_PROGRAM" > "$GITIGNORE_DEST"

echo -e "gitignore: ${CGREEN}created on ${GITIGNORE_DEST}"
