#!/usr/bin/bash
if [[ ! -d "${HOME}/.local/bin" ]]; then 
    echo "ERROR: can't find ${HOME}/.local/bin directory" >&2
    exit 1
fi

ROOT=$(dirname "$(realpath "$0")")
for tool in "$ROOT"/*; do
    [[ "${tool##*/}" != "${0##*/}" ]] || continue
    ln -s "$tool" "${HOME}/.local/bin/${tool##*/}"
done
